/**
 * Curated watchlists (static). “Top 50” foreign = large US/global equities;
 * Indian + Nifty = Nifty 50 constituents on NSE (.NS). Other tabs = sector/thematic.
 */

const nifty50Base = [
  ["ADANIENT", "Adani Enterprises"],
  ["ADANIPORTS", "Adani Ports"],
  ["APOLLOHOSP", "Apollo Hospitals"],
  ["ASIANPAINT", "Asian Paints"],
  ["AXISBANK", "Axis Bank"],
  ["BAJAJ-AUTO", "Bajaj Auto"],
  ["BAJFINANCE", "Bajaj Finance"],
  ["BAJAJFINSV", "Bajaj Finserv"],
  ["BPCL", "Bharat Petroleum"],
  ["BHARTIARTL", "Bharti Airtel"],
  ["BRITANNIA", "Britannia"],
  ["CIPLA", "Cipla"],
  ["COALINDIA", "Coal India"],
  ["DIVISLAB", "Divi's Labs"],
  ["DRREDDY", "Dr Reddy's"],
  ["EICHERMOT", "Eicher Motors"],
  ["GRASIM", "Grasim"],
  ["HCLTECH", "HCL Technologies"],
  ["HDFCBANK", "HDFC Bank"],
  ["HDFCLIFE", "HDFC Life"],
  ["HEROMOTOCO", "Hero MotoCorp"],
  ["HINDALCO", "Hindalco"],
  ["HINDUNILVR", "Hindustan Unilever"],
  ["ICICIBANK", "ICICI Bank"],
  ["ITC", "ITC"],
  ["INDUSINDBK", "IndusInd Bank"],
  ["INFY", "Infosys"],
  ["JSWSTEEL", "JSW Steel"],
  ["KOTAKBANK", "Kotak Bank"],
  ["LT", "Larsen & Toubro"],
  ["M&M", "Mahindra & Mahindra"],
  ["MARUTI", "Maruti Suzuki"],
  ["NESTLEIND", "Nestlé India"],
  ["NTPC", "NTPC"],
  ["ONGC", "ONGC"],
  ["POWERGRID", "Power Grid"],
  ["RELIANCE", "Reliance Industries"],
  ["SBILIFE", "SBI Life"],
  ["SBIN", "State Bank of India"],
  ["SUNPHARMA", "Sun Pharma"],
  ["TATACONSUM", "Tata Consumer"],
  ["TATAMOTORS", "Tata Motors"],
  ["TATASTEEL", "Tata Steel"],
  ["TCS", "Tata Consultancy Services"],
  ["TECHM", "Tech Mahindra"],
  ["TITAN", "Titan"],
  ["ULTRACEMCO", "UltraTech Cement"],
  ["UPL", "UPL"],
  ["WIPRO", "Wipro"],
  ["LTIM", "LTIMindtree"]
];

const foreign50 = [
  ["AAPL", "Apple"],
  ["MSFT", "Microsoft"],
  ["GOOGL", "Alphabet A"],
  ["AMZN", "Amazon"],
  ["META", "Meta"],
  ["NVDA", "NVIDIA"],
  ["TSLA", "Tesla"],
  ["JPM", "JPMorgan Chase"],
  ["V", "Visa"],
  ["UNH", "UnitedHealth"],
  ["XOM", "Exxon Mobil"],
  ["JNJ", "Johnson & Johnson"],
  ["MA", "Mastercard"],
  ["PG", "Procter & Gamble"],
  ["HD", "Home Depot"],
  ["CVX", "Chevron"],
  ["MRK", "Merck"],
  ["PEP", "PepsiCo"],
  ["COST", "Costco"],
  ["ABBV", "AbbVie"],
  ["BAC", "Bank of America"],
  ["KO", "Coca-Cola"],
  ["AVGO", "Broadcom"],
  ["PFE", "Pfizer"],
  ["WMT", "Walmart"],
  ["DIS", "Disney"],
  ["MS", "Morgan Stanley"],
  ["GS", "Goldman Sachs"],
  ["CAT", "Caterpillar"],
  ["BA", "Boeing"],
  ["LMT", "Lockheed Martin"],
  ["RTX", "RTX"],
  ["AMAT", "Applied Materials"],
  ["QCOM", "Qualcomm"],
  ["INTU", "Intuit"],
  ["NOW", "ServiceNow"],
  ["SPGI", "S&P Global"],
  ["BLK", "BlackRock"],
  ["C", "Citigroup"],
  ["USB", "U.S. Bancorp"],
  ["PLTR", "Palantir"],
  ["AMD", "AMD"],
  ["IBM", "IBM"],
  ["GE", "GE Aerospace"],
  ["MU", "Micron"],
  ["ADI", "Analog Devices"],
  ["SYK", "Stryker"],
  ["DE", "Deere"],
  ["TJX", "TJX Companies"],
  ["NFLX", "Netflix"]
];

const indianBseMix = [
  ["RELIANCE.BSE", "Reliance Industries"],
  ["TCS.BSE", "TCS"],
  ["HDFCBANK.BSE", "HDFC Bank"],
  ["ICICIBANK.BSE", "ICICI Bank"],
  ["INFY.BSE", "Infosys"],
  ["BHARTIARTL.BSE", "Bharti Airtel"],
  ["ITC.BSE", "ITC"],
  ["SBIN.BSE", "SBI"],
  ["LT.BSE", "Larsen & Toubro"],
  ["KOTAKBANK.BSE", "Kotak Bank"],
  ["AXISBANK.BSE", "Axis Bank"],
  ["ASIANPAINT.BSE", "Asian Paints"],
  ["MARUTI.BSE", "Maruti"],
  ["TITAN.BSE", "Titan"],
  ["SUNPHARMA.BSE", "Sun Pharma"],
  ["ULTRACEMCO.BSE", "UltraTech"],
  ["NESTLEIND.BSE", "Nestlé India"],
  ["POWERGRID.BSE", "Power Grid"],
  ["NTPC.BSE", "NTPC"],
  ["ONGC.BSE", "ONGC"],
  ["TATAMOTORS.BSE", "Tata Motors"],
  ["TATASTEEL.BSE", "Tata Steel"],
  ["JSWSTEEL.BSE", "JSW Steel"],
  ["WIPRO.BSE", "Wipro"],
  ["TECHM.BSE", "Tech Mahindra"],
  ["HCLTECH.BSE", "HCL Tech"],
  ["BAJFINANCE.BSE", "Bajaj Finance"],
  ["BAJAJFINSV.BSE", "Bajaj Finserv"],
  ["ADANIENT.BSE", "Adani Enterprises"],
  ["ADANIPORTS.BSE", "Adani Ports"],
  ["DIVISLAB.BSE", "Divi's Labs"],
  ["DRREDDY.BSE", "Dr Reddy's"],
  ["CIPLA.BSE", "Cipla"],
  ["EICHERMOT.BSE", "Eicher"],
  ["HEROMOTOCO.BSE", "Hero MotoCorp"],
  ["BRITANNIA.BSE", "Britannia"],
  ["COALINDIA.BSE", "Coal India"],
  ["BPCL.BSE", "BPCL"],
  ["UPL.BSE", "UPL"],
  ["GRASIM.BSE", "Grasim"],
  ["HINDALCO.BSE", "Hindalco"],
  ["APOLLOHOSP.BSE", "Apollo Hospitals"],
  ["SBILIFE.BSE", "SBI Life"],
  ["TATACONSUM.BSE", "Tata Consumer"],
  ["HDFCLIFE.BSE", "HDFC Life"],
  ["INDUSINDBK.BSE", "IndusInd Bank"],
  ["PIDILITIND.BSE", "Pidilite"],
  ["DABUR.BSE", "Dabur"],
  ["GODREJCP.BSE", "Godrej Consumer"],
  ["SIEMENS.BSE", "Siemens India"]
];

const mineralsCrude = [
  ["XOM", "Exxon Mobil"],
  ["CVX", "Chevron"],
  ["COP", "ConocoPhillips"],
  ["SLB", "Schlumberger"],
  ["EOG", "EOG Resources"],
  ["OXY", "Occidental"],
  ["MPC", "Marathon Petroleum"],
  ["PSX", "Phillips 66"],
  ["VLO", "Valero"],
  ["HAL", "Halliburton"],
  ["BKR", "Baker Hughes"],
  ["FANG", "Diamondback Energy"],
  ["DVN", "Devon Energy"],
  ["CTRA", "Coterra"],
  ["EQT", "EQT"],
  ["RIO", "Rio Tinto"],
  ["BHP", "BHP Group"],
  ["VALE", "Vale"],
  ["FCX", "Freeport-McMoRan"],
  ["SCCO", "Southern Copper"],
  ["AA", "Alcoa"],
  ["NUE", "Nucor"],
  ["STLD", "Steel Dynamics"],
  ["CLF", "Cleveland-Cliffs"],
  ["MT", "ArcelorMittal"],
  ["SHEL", "Shell"],
  ["BP", "BP ADR"],
  ["EQNR", "Equinor"],
  ["SU", "Suncor"],
  ["CNQ", "Canadian Natural"],
  ["IMO", "Imperial Oil"],
  ["WMB", "Williams"],
  ["KMI", "Kinder Morgan"],
  ["OKE", "ONEOK"],
  ["LNG", "Cheniere"],
  ["TRGP", "Targa Resources"],
  ["OVV", "Ovintiv"],
  ["AR", "Antero Resources"],
  ["MRO", "Marathon Oil"],
  ["CHK", "Chesapeake"],
  ["RRC", "Range Resources"],
  ["SWN", "Southwestern Energy"],
  ["MGY", "Magnolia Oil"],
  ["PR", "Permian Resources"],
  ["SM", "SM Energy"],
  ["MTDR", "Matador Resources"],
  ["NOV", "NOV Inc."],
  ["FTI", "TechnipFMC"],
  ["WFRD", "Weatherford"],
  ["HP", "Helmerich & Payne"]
];

/** Physical-backed bullion ETFs / trusts and COMEX futures only (no miners). */
const goldSilver = [
  ["GC=F", "Gold — COMEX futures"],
  ["MGC=F", "Micro gold futures"],
  ["GLD", "SPDR Gold Shares"],
  ["IAU", "iShares Gold Trust"],
  ["SGOL", "abrdn Physical Gold Shares"],
  ["GLDM", "SPDR Gold MiniShares"],
  ["BAR", "GraniteShares Gold Trust"],
  ["AAAU", "Goldman Sachs Physical Gold ETF"],
  ["OUNZ", "VanEck Merk Gold Trust"],
  ["PHYS", "Sprott Physical Gold Trust"],
  ["SI=F", "Silver — COMEX futures"],
  ["SIL=F", "Micro silver futures"],
  ["SLV", "iShares Silver Trust"],
  ["SIVR", "abrdn Physical Silver Shares"],
  ["PSLV", "Sprott Physical Silver Trust"]
];

const forex = [
  ["EURUSD", "Euro / US Dollar"],
  ["GBPUSD", "Pound / US Dollar"],
  ["USDJPY", "US Dollar / Yen"],
  ["AUDUSD", "Aussie / US Dollar"],
  ["USDCAD", "US Dollar / Canadian Dollar"],
  ["USDCHF", "US Dollar / Franc"],
  ["NZDUSD", "NZ Dollar / US Dollar"],
  ["USDINR", "US Dollar / Indian Rupee"],
  ["EURJPY", "Euro / Yen"],
  ["EURGBP", "Euro / Pound"],
  ["GBPJPY", "Pound / Yen"],
  ["AUDJPY", "Aussie / Yen"],
  ["USDMXN", "US Dollar / Mexican Peso"],
  ["USDZAR", "US Dollar / Rand"],
  ["USDSGD", "US Dollar / Singapore Dollar"],
  ["EURINR", "Euro / Indian Rupee"],
  ["GBPINR", "Pound / Indian Rupee"],
  ["USDTRY", "US Dollar / Turkish Lira"],
  ["USDSEK", "US Dollar / Swedish Krona"],
  ["USDNOK", "US Dollar / Norwegian Krone"]
];

const crypto = [
  ["BTC-USD", "Bitcoin"],
  ["ETH-USD", "Ethereum"],
  ["SOL-USD", "Solana"],
  ["XRP-USD", "XRP"],
  ["ADA-USD", "Cardano"],
  ["DOGE-USD", "Dogecoin"],
  ["DOT-USD", "Polkadot"],
  ["AVAX-USD", "Avalanche"],
  ["LINK-USD", "Chainlink"],
  ["MATIC-USD", "Polygon (MATIC)"],
  ["SHIB-USD", "Shiba Inu"],
  ["LTC-USD", "Litecoin"],
  ["BCH-USD", "Bitcoin Cash"],
  ["UNI-USD", "Uniswap"],
  ["ATOM-USD", "Cosmos"],
  ["XLM-USD", "Stellar"],
  ["ETC-USD", "Ethereum Classic"],
  ["FIL-USD", "Filecoin"],
  ["APT-USD", "Aptos"],
  ["ARB-USD", "Arbitrum"],
  ["OP-USD", "Optimism"],
  ["INJ-USD", "Injective"],
  ["NEAR-USD", "NEAR"],
  ["ICP-USD", "Internet Computer"],
  ["VET-USD", "VeChain"],
  ["HBAR-USD", "Hedera"],
  ["MKR-USD", "Maker"],
  ["AAVE-USD", "Aave"],
  ["GRT-USD", "The Graph"],
  ["RUNE-USD", "THORChain"]
];

function rows(entries) {
  return entries.map(([symbol, name]) => ({ symbol, name }));
}

const nifty50Ns = rows(nifty50Base.map(([s, n]) => [`${s}.NS`, n]));

export const TRENDING_MARKET_CATEGORIES = [
  {
    id: "foreign",
    title: "Foreign stocks",
    description: "50 large US & global equities (mega-cap & sector leaders).",
    symbols: rows(foreign50)
  },
  {
    id: "indian",
    title: "Indian stock market",
    description: "50 leading India listings (Indian API prioritized for this board).",
    symbols: rows(indianBseMix)
  },
  {
    id: "nifty50",
    title: "Nifty 50",
    description: "Nifty 50 style basket on NSE (.NS) — index-heavy names.",
    symbols: nifty50Ns
  },
  {
    id: "minerals_crude",
    title: "Minerals & crude oil",
    description: "Energy majors, oilfield services, metals & mining.",
    symbols: rows(mineralsCrude)
  },
  {
    id: "gold_silver",
    title: "Gold & silver",
    description: "Gold and silver only: COMEX futures plus physical-backed ETFs and trusts (no mining stocks).",
    symbols: rows(goldSilver)
  },
  {
    id: "forex",
    title: "Forex",
    description: "Major FX crosses (quote format e.g. EURUSD).",
    symbols: rows(forex)
  },
  {
    id: "crypto",
    title: "Crypto",
    description: "Top liquid crypto pairs (USD, Yahoo-style tickers).",
    symbols: rows(crypto)
  }
];

export function getTrendingCategoryById(id) {
  return TRENDING_MARKET_CATEGORIES.find((c) => c.id === id) || null;
}

export function listTrendingCategoryMeta() {
  return TRENDING_MARKET_CATEGORIES.map((c) => ({
    id: c.id,
    title: c.title,
    description: c.description,
    count: c.symbols.length
  }));
}
